const router = require('express').Router();
const { getAll, getOne, create, update, updateStatus, remove } = require('../controllers/orderController');
const { auth } = require('../middleware/auth');
router.get('/', auth, getAll);
router.get('/:id', auth, getOne);
router.post('/', auth, create);
router.put('/:id', auth, update);
router.patch('/:id/status', auth, updateStatus);
router.delete('/:id', auth, remove);
module.exports = router;
